### ISSUE TITLE
Centos 6 compilation verification

### ISSUE THREAD

**Issue by rk295** [fidian/bonkers#1]
All good on CentOS6, I've not plugged the button in yet, but here are the libusb packages I needed and proof it compiles without warnings/errors:

```
[robin@trin][~/GIT/bonkers]
master ❯ rpm -qv libusb1 libusb1-devel
libusb1-1.0.9-0.6.rc1.el6.i686
libusb1-devel-1.0.9-0.6.rc1.el6.i686
[robin@trin][~/GIT/bonkers]
master ❯ cat /etc/redhat-release
CentOS release 6.6 (Final)
[robin@trin][~/GIT/bonkers]
master ❯ make
gcc -Wall -O2 -o bonkers bonkers.c -lusb-1.0
[robin@trin][~/GIT/bonkers]
master ❯ ./bonkers
Failed opening device descriptor (you may need to be root)...
[robin@trin][~/GIT/bonkers]
master ❯
```

**Comment by fidian** [comment]
Wonderful!  Thanks for testing that for me.  Didn't I just tell you about this a couple minutes ago?  You're lightning quick.

You might want to do a pull.  I just committed some changes to clean up messages I saw in dmesg.
